#!name=Spotify
#!desc=解锁Premium,音质不能设置为超高.\n登录后再打开脚本,重启app等待脚本生效.
#!date=2026-05-08
#!category=🐹 BOBO Premium
#!author=app2smile[https://github.com/app2smile],Amlabort[https://github.com/Amlabort/MY_clash]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/App/Spotify.png
#!openUrl=https://apps.apple.com/app/id324684580

[filter_local]
DOMAIN-SUFFIX,spotify.com,REJECT-QUIC
DOMAIN,aet.spotify.com,REJECT

[rewrite_local]
# > Spotify解锁Premium
^https:\/\/(spclient\.wg|.*-spclient)\.spotify\.com(:443)?\/pendragon url reject-200
# 屏蔽设置界面会员信息（仅改变显示）
^https:\/\/.*-spclient\.spotify\.com(:443)?\/pam-view-service\/ url reject-200
# 屏蔽 AI DJ
^https:\/\/.*37i9dQZF1EYkqdzj48dyYq.* url reject-200

# 去广告
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/browsita\/v.\/browse url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/Spotify/JS/JS-3/JS/Spotify-NoSearchAd.js
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/casita\/v.\/home\/default url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/Spotify/JS/JS-3/JS/Spotify-NoHomeAd.js
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/scrollsita\/v.\/scroll\/spotify url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/Spotify/JS/JS-3/JS/Spotify-NoScrollAd.js

^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/Spotify/JS/JS-1/Spotify-QX-Header.js
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$ url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/Spotify/JS/JS-3/JS/Spotify-Proto-Eevee3.js
^https:\/\/(.*-spclient\.spotify\.com(:443)?|spclient\.wg\.spotify\.com)\/gabo-receiver-service url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/Spotify/JS/JS-3/JS/Spotify-GaBo.js

[mitm]
hostname = spclient.wg.spotify.com, *spclient.spotify.com
