#!name=Apple证书屏蔽验证
#!desc=精准屏蔽 Apple p12证书验证，让已过期证书能够继续使用
#!date=2026-05-30
#!category=🐹 BOBO Enhance
#!author=Salem[https://github.com/salem-2007/apple-cert-block]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/Qure/Image/Color/Apple_Update.png

[filter_local]
# Apple OCSP
host, ocsp.apple.com, reject
host, ocsp2.apple.com, reject

# Apple Validation
host, valid.apple.com, reject
host, ppq.apple.com, reject
host, ppq-ext.v.aaplimg.com, reject

# Apple CRL
host, crl.apple.com, reject
host, certs.apple.com, reject

# DigiCert
host, ocsp.digicert.com, reject
host, ocsp.digicert.cn, reject
host, crl3.digicert.com, reject
host, crl4.digicert.com, reject

# Entrust
host, ocsp.entrust.net, reject
host, crl.entrust.net, reject

# Sectigo / USERTrust
host, ocsp.sectigo.com, reject
host, crl.sectigo.com, reject
host, ocsp.usertrust.com, reject
host, crl.usertrust.com, reject

[mitm]
hostname = ocsp.apple.com, ocsp2.apple.com, valid.apple.com
