#!name= X网页版会员标签页
#!desc= X网页版会员标签页
#!date=2026-05-30
#!category=🐹 BOBO Premium
#!author=奶思fmz200[https://github.com/fmz200/wool_scripts]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/App/X-01.png
#!openUrl=https://x.com/

[rewrite_local]
# > X网页版会员标签页
^https?:\/\/x\.com\/i\/api\/graphql\/[^\/]+\/PinnedTimelines\? url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/X/JS/XWebEnhance.js

[mitm]
hostname = x.com
