#!name=蛋蛋不语 VIP 解锁
#!desc=蛋蛋不语 VIP 解锁
#!date=2026-06-01
#!category=🐹 BOBO Premium
#!author=Curtinp118[https://github.com/curtinp118]
#!openUrl=https://danboxingqiu.cn

[rewrite_local]
# > 蛋蛋不语 VIP 解锁
^http:\/\/38\.76\.202\.248:8000\/.*profiles.* url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/DanDan_VIP/JS/DanDan_VIP.js

[mitm]
hostname = 38.76.202.248
