#!name=Revenuecat 系列解锁
#!desc=支持一键解锁 RevenueCat、Superwall 和 Adapty (Adapty 需卸载重装 App 才生效)。\n如果遇到解锁后报错或闪退的 App (比如 Filebar)，可以直接在模块设置里填名字跳过它！\n(默认填 '-' 代表全部 App 正常解锁).\n可在 BoxJS [Reven 解锁设置] 中配置: reven_mock / reven_bypass
#!date=2026-05-04
#!category=🐹 BOBO Premium
#!author=baby[https://github.com/Yu9191]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/App/RevenueCat-icon.png

[rewrite_local]
# > Revenuecat 系列解锁
^https:\/\/(api\.revenuecat\.com|api\.rc-backup\.com|rc\.visionarytech\.ltd|revenue\.cuto\.app|proxy\.linearity\.io)\/(.+\/(?:receipts|subscribers\/[^/]+(?:\/attributes)?))$ url script-analyze-echo-response https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/Revenuecat/JS/JS-6/JS/Reven-QX.js#bypass=-
^https:\/\/subscriptions-api\.superwall\.com\/(.+) url script-analyze-echo-response https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/Revenuecat/JS/JS-6/JS/Reven-QX.js#bypass=-
^https:\/\/api\.adapty\.io\/(.+) url script-analyze-echo-response https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/Revenuecat/JS/JS-6/JS/Reven-QX.js#bypass=-

[mitm]
hostname = api.revenuecat.com, api.rc-backup.com, rc.visionarytech.ltd, revenue.cuto.app, proxy.linearity.io, subscriptions-api.superwall.com, api.adapty.io
