#!name=Google Maps 卫星地图偏移修复
#!desc=Google Maps 卫星地图偏移修复
#!date=2026-07-12
#!category=🐹 BOBO Enhance
#!author= Ning33274[https://github.com/Ning33274/fuck-google-maps-offset]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/App/GoogleMaps.png

[rewrite_local]
# > Google Maps 卫星地图偏移修复
^https:\/\/mobilemaps\.googleapis\.com\/maps\/vt\/proto\? url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/GoogleMaps.Offset.Fix/JS/GoogleMaps.Offset.Fix.js

[mitm]
hostname = mobilemaps.googleapis.com
