#!name=GitHub源文件自动CDN
#!desc=将 GitHub Raw 请求自动重定向到 CDN
#!date=2026-05-30
#!category=🐹 BOBO Enhance
#!author=桂林仔Yuheng0101[https://github.com/Yuheng0101/X]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/App/Git-To-CDN.png

[rewrite_local]
# > GitHub源文件自动CDN
https?://raw\.githubusercontent\.com/.+ url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/GitRawAutoCDN/JS/GitRawAutoCDN.js

[mitm]
hostname = raw.githubusercontent.com
