#!name =  iRingo: 📍 LocationService
#!desc = 自定义定位服务内容\n添加国际版功能\n自定义服务版本
#!date=2026-07-30
#!category =  iRingo
#!author = VirgilClyne[https://github.com/VirgilClyne]
#!homepage = https://NSRingo.github.io/guide/GeoServices/location-service
#!icon = https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/IMG/iRingo/Location.jpg
#!openUrl = http://boxjs.com/#/app/iRingo.LocationService

[filter_local]
# 📍 Country Code
host, gspe1-ssl.ls.apple.com, direct
# 📍 Amap Dispatcher
host, dispatcher.is.autonavi.com, direct

[rewrite_local]
# 📍 Country Code
^https?:\/\/gspe1-ssl\.ls\.apple\.com\/pep\/gcc url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/iRingo/LocationService/JS/request.bundle.js
# 📍 Dispatcher
^https?:\/\/dispatcher\.is\.autonavi\.com\/dispatcher url script-request-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/iRingo/LocationService/JS/request.bundle.js
^https?:\/\/dispatcher\.is\.autonavi\.com\/dispatcher url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/iRingo/LocationService/JS/response.bundle.js

[mitm]
hostname = gspe1-ssl.ls.apple.com, dispatcher.is.autonavi.com
