#!name=YouTube 强制简体中文字幕
#!desc=YouTube 强制简体中文字幕
#!date=2026-04-13
#!category=🐹 BOBO Enhance
#!author=ZenmoFeiShi[https://github.com/ZenmoFeiShi/Qx],Claude[https://claude.ai/]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/App/YouTube.png

[rewrite_local]
# > YouTube 强制简体中文字幕
^https://www\.youtube\.com/api/timedtext\?.*_ytzhsub=1 url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/YouTube/JS/JS-4/JS/YT-Sub-Clean.js
^https://www\.youtube\.com/api/timedtext\? url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/YouTube/JS/JS-4/JS/YT-ZH-Sub.js

[mitm]
hostname = www.youtube.com
