#!name=起点读书自动签到
#!desc=签到结果通知（含账号昵称、时间、状态）
#!date=2026-05-08
#!category=🐹 BOBO Task
#!author=桂林仔Yuheng0101[https://github.com/Yuheng0101/X]

[rewrite_local]
# > 起点读书获取Cookie
^https?:\/\/h5\.if\.qidian\.com\/argus\/api\/v1\/user\/getlogininfo url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/QDReader/JS/QDReader.js

[task_local]
30 9 * * * https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/QDReader/JS/QDReader.js, tag=起点读书自动签到, enabled=true

[mitm]
hostname = h5.if.qidian.com
