#!name =  iRingo: 🗺️ Maps
#!desc = 自定义 Maps app\n添加国际版功能\n自定义服务版本
#!date=2026-07-30
#!category =  iRingo
#!author = VirgilClyne[https://github.com/VirgilClyne]
#!homepage = https://NSRingo.github.io/guide/GeoServices/maps
#!icon = https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/IMG/iRingo/Maps.png
#!openUrl = http://boxjs.com/#/app/iRingo.Maps

[filter_local]
# 🗺️ Amap
host-suffix, is.autonavi.com, direct
# 🗺️ Maps
host, gspe11-2-cn-ssl.ls.apple.com, direct
host, gspe12-cn-ssl.ls.apple.com, direct
host, gspe19-cn-ssl.ls.apple.com, direct
host, gspe19-2-cn-ssl.ls.apple.com, direct
host, gspe79-cn-ssl.ls.apple.com, direct

[rewrite_local]
# 🗺️ Network Defaults
^https?:\/\/configuration\.ls\.apple\.com\/config\/defaults url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/iRingo/Maps/JS/request.bundle.js
^https?:\/\/configuration\.ls\.apple\.com\/config\/defaults url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/iRingo/Maps/JS/response.bundle.js
# 🗺️ Announcements
^https?:\/\/gspe35-ssl\.ls\.apple\.(com|cn)\/config\/announcements url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/iRingo/Maps/JS/request.bundle.js
^https?:\/\/gspe35-ssl\.ls\.apple\.(com|cn)\/config\/announcements url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/iRingo/Maps/JS/response.bundle.js
# 🗺️ Resource Manifest
^https?:\/\/gspe35-ssl\.ls\.apple\.(com|cn)\/geo_manifest\/dynamic\/config url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/iRingo/Maps/JS/request.bundle.js
^https?:\/\/gspe35-ssl\.ls\.apple\.(com|cn)\/geo_manifest\/dynamic\/config url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/iRingo/Maps/JS/response.bundle.js

[mitm]
hostname = configuration.ls.apple.com, gspe35-ssl.ls.apple.com
