#!name=PingMe-电话小号自动化签到
#!desc=PingMe自动化签到+视频奖励.\n定时每天运行两次.\n大概20天可白嫖一个DC1的TG号，一年12个tg号
#!date=2026-05-11
#!category=🐹 BOBO Task
#!author=怎么肥事ZenmoFeiShi[https://github.com/ZenmoFeiShi/Qx]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/App/PingMe.png
#!openUrl=https://apps.apple.com/app/id1444762648

[rewrite_local]
^https:\/\/api\.pingmeapp\.net\/app\/queryBalanceAndBonus url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/PingMe/JS/PingMe.js

[task_local]
30 8,20 * * * https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/PingMe/JS/PingMe.js, tag=PingMe签到, enabled=true

[mitm]
hostname = api.pingmeapp.net
