#!name=GLaDOS / Railgun 自动签到
#!desc=GLaDOS / Railgun 自动签到 + 积分兑换（多账号版）
#!date=2026-05-30
#!category=🐹 BOBO Task
#!author=Curtinp118[https://github.com/curtinp118]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/App/GLaDOS.png
#!openUrl=https://glados.vip/

[rewrite_local]
# > GLaDOS 自动签到
^https:\/\/glados\.network\/console\/account$ url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/GLaDOS/JS/GLaDOS.js
^https:\/\/railgun\.info\/console\/account$ url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/GLaDOS/JS/GLaDOS.js
^https:\/\/glados\.vip\/console\/account$ url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/GLaDOS/JS/GLaDOS.js

[task_local]
30 7 * * * https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/GLaDOS/JS/GLaDOS.js, tag=GLaDOS 签到, enabled=true

[mitm]
hostname = glados.network, glados.vip, railgun.info
