#!name=节点连通性检测脚本
#!desc=检测当前节点是否可连接，并判断是否被运营商/GFW 阻断
#!date=2026-07-17
#!category=🐹 BOBO Enhance
#!author=RavelloH[https://gist.githubusercontent.com/RavelloH/383354955aa3800e1d7e98666e11e16f/raw/block_check.js]

[task_local]
event-interaction https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/Block_Check/JS/JS-1/Block_Check.js, tag=节点阻断检测, img-url=img-url=bolt.horizontal.icloud.fill.system, enabled=true
