#!name = 📺 BiliBili: ⚙️ Enhanced
#!desc = 哔哩哔哩：增强模式\n中国站功能增强及UI自定义
#!date=2026-07-30
#!category = 🪐 BiliUniverse
#!author = VirgilClyne[https://github.com/VirgilClyne]
#!homepage = https://biliuniverse.github.io/guide/enhanced
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/BiliUniverse/Enhanced/JS/IMG/icon_rounded.png
#!openUrl = http://boxjs.com/#/app/BiliBili.Enhanced

[rewrite_local]
# 📺 BiliBili.Enhanced.x.resource.show.tab.v2
^https?:\/\/app\.bili(bili\.com|api\.net)\/x\/resource\/show\/tab\/v2\? url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/BiliUniverse/Enhanced/JS/response.bundle.js
# 📺 BiliBili.Enhanced.x.v2.account.mine
^https?:\/\/app\.bili(bili\.com|api\.net)\/x\/v2\/account\/mine(\/ipad)?\? url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/BiliUniverse/Enhanced/JS/response.bundle.js
# 📺 BiliBili.Enhanced.x.v2.region.index
^https?:\/\/app\.bili(bili\.com|api\.net)\/x\/v2\/region\/index\? url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/BiliUniverse/Enhanced/JS/response.bundle.js
# 📺 BiliBili.Enhanced.x.v2.channel.region.list
^https?:\/\/app\.bili(bili\.com|api\.net)\/x\/v2\/channel\/region\/list\? url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/BiliUniverse/Enhanced/JS/response.bundle.js

[mitm]
hostname = app.bilibili.com, app.biliapi.net
