#!name=人人追剧
#!desc=解锁会员权限
#!date=2026-05-30
#!category=🐹 BOBO Premium
#!author=桂林仔Yuheng0101[https://github.com/Yuheng0101/X]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/App/RenRenZhuiJu.png
#!openUrl=https://apps.apple.com/app/id6761045519

[rewrite_local]
# > 人人追剧解锁会员权限
https?:\/\/burst\.hnaiz\.com\/represent\/(walk\/class|itself\/set|them\/media) url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/RenRenZhuiJu/JS/RenRenZhuiJu.js

[mitm]
hostname = burst.hnaiz.com
