#!name=Plex - Rewrite display username重写显示用户名
#!desc=修改 Plex 用户 API 响应中的 title、friendlyName 和 username 字段
#!date=2026-07-11
#!category=🐹 BOBO Enhance
#!author=liunice[https://github.com/liunice/quantumult-x-rewrites]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/App/Plex.png

[rewrite_local]
^https://clients\.plex\.tv/api/v2/user\? url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/Plex/JS/Plex.js
^https://clients\.plex\.tv/api/v2/home/users url script-response-body https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/JS/Plex/JS/Plex.js

[mitm]
hostname = clients.plex.tv
