#!name=贴吧签到
#!desc=自动签到贴吧.\n打开百度贴吧APP点击"我的"即可获取cookie.
#!date=2026-08-14
#!category=🐹 BOBO Task
#!author= NobyDa[https://github.com/NobyDa/Script]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/miniColor/Image/Color/tieba.png
#!openUrl=https://apps.apple.com/app/id477927812

[rewrite_local]
# > 百度贴吧 cookie
^https?:\/\/(c\.tieba|tiebac)\.baidu\.com\/c\/s\/login url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/BaiDuTieBa/JS/JS-1/BaiDuTieBa.js

[task_local]
# > 贴吧签到
10,20,30 9 * * * https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/BaiDuTieBa/JS/JS-1/BaiDuTieBa.js, tag=贴吧签到, img-url=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/miniColor/Image/Color/tieba.png, enabled=true

[mitm]
hostname = tiebac.baidu.com, c.tieba.baidu.com
