#!name=学术FUN-AI工具整合包 自动签到
#!desc=自动获取 xueshu.fun 的 Cookie/UA 并每日自动签到
#!date=2026-08-19
#!category=🐹 BOBO Task
#!author= BOBOLAOSHIV587[https://github.com/BOBOLAOSHIV587/Rules],Claude[https://claude.ai/]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/AppIcons/Image/App/XueShuFUN.png
#!openUrl=https://xueshu.fun/

[rewrite_local]
# > 学术FUN获取Cookie
^https:\/\/xueshu\.fun\/wp-admin\/admin-ajax\.php url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/XueShuFUN/JS/Get-Cookie.js

[task_local]
# > 学术FUN签到
10 8 * * * https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/XueShuFUN/JS/CheckIn.js, tag=学术FUN签到, enabled=true

[mitm]
hostname = xueshu.fun
