#!name=贴吧签到
#!desc=自动签到贴吧。获取Cookie说明：打开百度贴吧App后, 如通知成功获取cookie, 则可以使用此签到脚本。
#!date=2026-08-14
#!category=🐹 BOBO Task
#!author= ClydeTime[https://github.com/ClydeTime/Quantumult]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/miniColor/Image/Color/tieba.png

[rewrite_local]
# > 百度贴吧 cookie
^https?:\/\/tiebac\.baidu\.com\/c\/u\/follow\/getFoldedMessageUserInfo url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/BaiDuTieBa/JS/BaiDuTieBa.js
^https?:\/\/c\.tieba\.baidu\.com\/c\/u\/follow\/getFoldedMessageUserInfo url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/BaiDuTieBa/JS/BaiDuTieBa.js

[task_local]
# > 贴吧签到
10,20,30 9 * * * https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/BaiDuTieBa/JS/BaiDuTieBa.js, tag=贴吧签到, img-url=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Icons/miniColor/Image/Color/tieba.png, enabled=true

[mitm]
hostname = tiebac.baidu.com, c.tieba.baidu.com
