#!name=WhosTV 自动签到
#!desc=自动抓取 whos.tv Cookie，每日签到，并通过客户端本地通知结果。
#!date=2026-08-01
#!category=🐹 BOBO Task
#!author=imzwr214[https://github.com/imzwr214/whos]
#!icon=https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/WhosTV/JS/IMG/WhosTV.png
#!openUrl=https://whos.tv/

[rewrite_local]
https://whos.tv/api/ url script-request-header https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/WhosTV/JS/JS-1/WhosTV.js

[task_local]
30 8 * * * https://raw.githubusercontent.com/BOBOLAOSHIV587/Rules/main/Task/WhosTV/JS/JS-1/WhosTV.js, tag=WhosTV 自动签到, enabled=true

[mitm]
hostname = whos.tv
